version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/DockerFile
      args:
        UID: ${UID}
        GID: ${GID}
    user: "${UID}:${GID}"
    image: laravel-api
    container_name: store-fake-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - mysql

  nginx:
    image: nginx:stable-alpine
    container_name: store-fake-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: store-fake-mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata: